## log 設定
log:
  app_id: test_conn
  env: local
  level: 0
  local: true

http:
  port: 8080
  debug: true
  mode: release

### grpc
grpc:
  address: 0.0.0.0:8090
  debug: true

# Client config
client:
  test_conn:
    addr: 0.0.0.0
    port: 8090
