apiVersion: v1
kind: Service
metadata:
  name: test-conn-server-svc
spec:
  ports:
    - port: 8090
      name: grpc
      targetPort: 8090
  selector:
    app: test-conn-server
---
apiVersion: v1
kind: Service
metadata:
  name: test-conn-client-svc
spec:
  ports:
    - port: 8090
      name: grpc
      targetPort: 8090
  selector:
    app: test-conn-client
